name: Drama Watcher TG Bot

on:
  schedule:
    # Jalan otomatis setiap 4 Jam sekali
    - cron: '0 */4 * * *' 
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Auto-Save Progress to Github
        if: always() 
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add selesai.json || true
          git add config.json || true
          git commit -m "Auto save progress [skip ci]" || echo "Tidak ada perubahan"
          git push
